resolver: lts-13.19

packages:
- .

extra-deps:
- accelerate-1.2.0.1
- accelerate-llvm-1.2.0.1
- accelerate-llvm-native-1.2.0.1
- llvm-hs-8.0.0
- llvm-hs-pure-8.0.0
- tasty-hedgehog-0.2.0.0
- gloss-accelerate-2.0.0.1

flags:
  llvm-hs:
    shared-llvm: true
